character/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static

app_name = 'character'
urlpatterns = [

    # 캐릭터 생성 관련 페이지

    path('character/list', character_list, name='character_list'),  # 생성한 캐릭터 리스트 페이지

    path('character/detail/<int:pk>', character_detail, name='character_detail'),  # 캐릭터 디테일 페이지

    path('character/create', character_create, name='character_create'),  # 캐릭터 5개 있는 페이지 선택

    # 캐릭터 하나를 선택하고 들어온 그 text 페이지 여기서는 선택이유 쓰면 됨  결국 이 텍스트는 introudce에 저장 추가로 캐릭터 이름도 적어야됨
    path('character/create/<int:pk>', character_create_detail, name='character_create_detail'),

    path('character/update/<int:pk>', character_update, name='character_update'),
    # 캐릭터 이름만 수정                   {{ 차이 }} --> 캐릭터의 이름은 감정 그 자체로 해서 변화시킬 수 없는것으로 구상한것이었음

    path('trash/delete/<int:pk>', trash_delete, name='trash_delete'),  # 이거는 캐릭터 삭제버튼 url 즉 휴지통으로  이동 post 만 접속가능하게 해야됨

    path('trash', trash, name='trash'),  # 여기는 삭제된 캐릭터의 휴지통 페이지

    path('trash/restore/<int:pk>', trash_restore, name='trash_restore'),
    # 여기는 휴지통에서 캐릭터 선택하면 복구하는 페이지 만약 복구했는데 캐릭터 5개이면 복구못하게

    path('trash/perfect/delete/<int:pk>', trash_perfect_delete, name='trash_perfect_delete'),
    # 이거는 캐릭터 영구 삭제 url 즉 휴지통에서만 작동할수 있는 url임


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chatbot/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import *

app_name = 'chatbot'
urlpatterns = [

    # AI 챗봇 관련 페이지
    # 여기서 핵심은 AJAX로 불러올거라서 대화내용을 개개인 마다 list url 설정해서 뭐 안해도됨

    path('chatbot/<int:pk>', chatbot_content_list, name='chatbot_content_list'),  # pk는 캐릭터의 식별자임 챗봇의 식별자 아님!!

    path('chatbot/ai/create/<int:pk>', chatbot_ai_create, name='chatbot_ai_create'),  # pk는 캐릭터의 식별자 유저는 세션에서 불러올거니깐

    path('chatbot/user/create/<int:pk>', chatbot_user_create, name='chatbot_user_create'),
    # pk는 캐릭터의 식별자 유저는 세션에서 불러올거니깐

    path('tts/', tts, name='tts'), # 녹음 음성 인식 변화ㅏㄴ
    # 감정 기록 페이지
    path('emotion/', emotion, name='emotion'),
    # path('weekly_emotion_log/', weekly_emotion_log, name='weekly_emotion_log'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


# 404 핸들러
from django.shortcuts import render

def custom_page_not_found_view(request, exception):
    return render(request, '404.html', {}, status=404)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('feedback.urls')),
    path('', include('chatbot.urls')),
    path('', include('character.urls')),
    path('accounts/', include('allauth.urls')), #소셜로그인

]

# DEBUG가 False여도 미디어 파일 서빙 가능하게 설정
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# 이미지 파일 서빙을 위해 추가
# if not settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# 404 핸들러 설정
handler404 = 'config.urls.custom_page_not_found_view'

feedback/urls.py
from django.urls import path
from .views import *

app_name = 'feedback'
urlpatterns = [
    path('community/', feedback_list, name='feedback_list'),
    path('community/create/', feedback_create, name='feedback_create'),
    path('community/delete/<int:pk>/', feedback_delete, name='feedback_delete'),
    path('community/detail/<int:pk>/', feedback_detail, name='feedback_detail'),
    path('edit/<int:pk>/', feedback_edit, name='feedback_edit'),
]

users/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

app_name = 'users'

urlpatterns = [

    # 메인
    path('', main, name='main'),

    # 회원
    path('signup/', signup, name='signup'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('profile/', profile, name='profile'),

    #비밀번호 찾기
    path('password_reset/', password_reset_request, name='password_reset'), #비밀번호 재설정 요청 폼
    path('password_reset/done/', password_reset_done, name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', password_reset_confirm, name='password_reset_confirm'), #새 비밀번호 설정 폼
    path('password_reset_complete/', password_reset_complete, name='password_reset_complete'), #비밀번호 재설정 완료 페이지
]

character/models.py
from django.db import models
from users.models import User
from django.conf import settings

# Create your models here.
# 사용자가 생성한 캐릭터 테이블
# 감정과 이미지 파일의 매핑을 위한 상수 정의
EMOTION_CHOICES = [
    ('angry', 'Angry'),
    ('anxiety', 'Anxiety'),
    ('fear', 'Fear'),
    ('joy', 'Joy'),
    ('sad', 'Sad'),
]


class AdminCharacter(models.Model):
    emotion = models.CharField(max_length=10, choices=EMOTION_CHOICES, unique=True)
    image = models.ImageField(upload_to='images/', blank=True, null=True)
    gif = models.FileField(upload_to='images/', blank=True, null=True)


class UserCharacter(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)  # 유저 식별자
    adminCharacter = models.ForeignKey(AdminCharacter, on_delete=models.CASCADE)  # 초기 캐릭터 식별자
    introduce = models.TextField()  # 생성 이유
    last_content = models.TextField(default=" ")  # 인공지능 마지막 대화
    trash = models.BooleanField(default=False)  # 캐릭터 휴지통 플래그
    name = models.CharField(max_length=30)  # 캐릭터 이름

    def __str__(self):
        return self.name

character/forms.py
from django import forms
from .models import AdminCharacter, UserCharacter
from django.conf import settings


class UserCharacterForm(forms.ModelForm):
    class Meta:
        model = UserCharacter
        fields = ['name', 'introduce', 'adminCharacter']
        widgets = {'adminCharacter': forms.HiddenInput()}  # 필드를 숨김으로 설정

    def __init__(self, *args, **kwargs):
        super(UserCharacterForm, self).__init__(*args, **kwargs)
        self.fields['adminCharacter'].queryset = AdminCharacter.objects.all()
        self.fields['adminCharacter'].required = False  # 필수 항목이 아님


class UserCharacterNameForm(forms.ModelForm):
    class Meta:
        model = UserCharacter
        fields = ['name']  # 이름만 수정 가능

character/views.py
from django.http import HttpResponseForbidden, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.csrf import csrf_exempt

from .models import UserCharacter
from django.contrib.auth.models import AnonymousUser  # 로그인 기능없이 테스트를 해보기 위해서
from .forms import UserCharacterNameForm

from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from .models import AdminCharacter
from .forms import UserCharacterForm


# Create your views here.

@login_required
def character_list(request):
    if isinstance(request.user, AnonymousUser):
        user_characters = []  # 빈 리스트로 설정하거나 다른 처리를 할 수 있습니다.
    else:
        first_item = UserCharacter.objects.filter(user=request.user, trash=False).first()
        user_characters = UserCharacter.objects.filter(user=request.user, trash=False)
        context = {
            'first_item': first_item,
            'user_characters': user_characters
        }
    return render(request, 'character/character_list.html', context)


@login_required
def character_detail(request, pk):
    if request.method == 'POST':
        characterEdit = UserCharacter.objects.get(pk=pk)
        characterEdit.name = request.POST.get('name')
        characterEdit.introduce = request.POST.get('introduce')
        characterEdit.save()
        return redirect('character:character_list')
    character = UserCharacter.objects.get(pk=pk)
    context = {
        'character': character
    }

    return render(request, 'character/character_detail.html', context)


def character_create(request):
    admin_characters = AdminCharacter.objects.all()
    user_characters = UserCharacter.objects.filter(user=request.user)

    # user2가 가진 모든 AdminCharacter 객체의 ID를 리스트로 추출
    user_character_ids = [uc.adminCharacter.id for uc in user_characters if uc.adminCharacter]

    context = {'admin_characters': admin_characters, 'user_character_ids': user_character_ids}
    return render(request, 'character/character_create.html', context)


@login_required
def character_create_detail(request, pk):
    admin_character = get_object_or_404(AdminCharacter, pk=pk)

    if request.method == 'POST':
        form = UserCharacterForm(request.POST)
        if form.is_valid():
            user_character = form.save(commit=False)
            user_character.adminCharacter = admin_character
            user_character.user = request.user
            user_character.save()
            return redirect('character:character_list')
        else:
            print(form.errors)  # 폼 에러 메시지 출력
    else:
        form = UserCharacterForm(initial={'adminCharacter': admin_character})

    return render(request, 'character/character_create_detail.html', {'admin_character': admin_character, 'form': form})


@login_required
def character_update(request, pk):
    user_character = get_object_or_404(UserCharacter, pk=pk, user=request.user)

    if request.method == 'POST':
        form = UserCharacterNameForm(request.POST, instance=user_character)
        if form.is_valid():
            form.save()
            return redirect('character:character_list')  # 수정 후 캐릭터 리스트로 리다이렉트
    else:
        form = UserCharacterNameForm(instance=user_character)

    return render(request, 'character/character_update.html', {'form': form, 'user_character': user_character})


@login_required
def trash_delete(request, pk):
    if request.method == 'POST':
        UserCharacter.objects.filter(id=pk).update(trash=True)

        return redirect('character:character_list')  # 적절한 리다이렉트 URL로 변경 필요
    return JsonResponse({'success': False}, status=400)


@login_required
def trash(request):
    character_trash = UserCharacter.objects.filter(user=request.user, trash=True)
    first_item = UserCharacter.objects.filter(user=request.user, trash=False).first()
    context = {'character_trash': character_trash, 'first_item': first_item}
    return render(request, 'character/trash.html', context)


@login_required
def trash_restore(request, pk):
    if request.method == 'POST':
        character = UserCharacter.objects.get(pk=pk)
        character.trash = False
        character.save()
    return redirect('character:character_list')


@login_required
def trash_perfect_delete(request, pk):
    if request.method == 'POST':
        character = UserCharacter.objects.get(pk=pk)
        character.delete()
    return redirect('character:trash')

templates/character/character_update.html
<!-- character/character_update.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update Character Name</title>
</head>
<body>
    <h1>Update Character Name: {{ user_character.name }}</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save Changes</button>
    </form>
</body>
</html>

templates/character/trash.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FeelBuddy</title>
    <link rel="icon" href="/media/joy.png" type="image/png">
    <link rel="stylesheet" href="{% static '/css/trash/trash.css' %}">
    <link rel="stylesheet" href="{% static '/css/chatbot/icon.css' %}">
    <meta name="csrf-token" content="{{ csrf_token }}">
    <link rel="stylesheet" href="{% static '/css/chatbot/nav.css' %}">

</head>

<body>

<header class="chat-header" id="header">
    <div class="header-left">
        <a href="{% url 'feedback:feedback_list' %}" class="header-feedback">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor">
                <path d="M21.9024 10.5976C21.4442 10.5333 20.976 10.5 20.5 10.5C17.2404 10.5 14.3455 12.0604 12.5212 14.471C12.3501 14.4887 12.1763 14.4978 12 14.4978C10.7188 14.4978 9.55217 14.0172 8.66691 13.2248L7.33309 14.7151C8.41871 15.6868 9.81141 16.3253 11.3466 16.4676C10.8023 17.7016 10.5 19.0662 10.5 20.5C10.5 20.976 10.5333 21.4442 10.5976 21.9024C5.7387 21.2205 2 17.0469 2 12C2 6.47715 6.47715 2 12 2C17.0469 2 21.2205 5.7387 21.9024 10.5976ZM21.8707 12.617C21.4254 12.5401 20.9674 12.5 20.5 12.5C17.7656 12.5 15.3512 13.8709 13.9068 15.9675C13.0194 17.2556 12.5 18.8156 12.5 20.5C12.5 20.9674 12.5401 21.4254 12.617 21.8707L21.8707 12.617ZM8.5 11.5C9.32843 11.5 10 10.8284 10 10C10 9.17157 9.32843 8.5 8.5 8.5C7.67157 8.5 7 9.17157 7 10C7 10.8284 7.67157 11.5 8.5 11.5ZM15.5 11.5C16.3284 11.5 17 10.8284 17 10C17 9.17157 16.3284 8.5 15.5 8.5C14.6716 8.5 14 9.17157 14 10C14 10.8284 14.6716 11.5 15.5 11.5Z"></path>
            </svg>
        </a>
    </div>
    <span><p>Feel Buddy</p></span>
    <div class="header-right">
        <a class="header-logout logout-btn">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor">
                <path d="M12 22C6.47715 22 2 17.5228 2 12C2 6.47715 6.47715 2 12 2C15.2713 2 18.1757 3.57078 20.0002 5.99923L17.2909 5.99931C15.8807 4.75499 14.0285 4 12 4C7.58172 4 4 7.58172 4 12C4 16.4183 7.58172 20 12 20C14.029 20 15.8816 19.2446 17.2919 17.9998L20.0009 17.9998C18.1765 20.4288 15.2717 22 12 22ZM19 16V13H11V11H19V8L24 12L19 16Z"></path>
            </svg>
            <!-- <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor"><path d="M5 22C4.44772 22 4 21.5523 4 21V3C4 2.44772 4.44772 2 5 2H19C19.5523 2 20 2.44772 20 3V6H18V4H6V20H18V18H20V21C20 21.5523 19.5523 22 19 22H5ZM18 16V13H11V11H18V8L23 12L18 16Z"></path></svg> -->
        </a>
    </div>

</header>

<nav class="mobile-footer" role="menulist">
    <a href="{% url 'character:character_list' %}" role="menuitem" aria-describedby="nav-current">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor">
            <path
                    d="M20 20C20 20.5523 19.5523 21 19 21H5C4.44772 21 4 20.5523 4 20V11L1 11L11.3273 1.6115C11.7087 1.26475 12.2913 1.26475 12.6727 1.6115L23 11L20 11V20ZM11 13V19H13V13H11Z">
            </path>
        </svg>
        Home
    </a>
    {% if first_item %}
        <a href="{% url 'chatbot:chatbot_content_list' first_item.pk %}">

            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor">
                <path
                        d="M10 3H14C18.4183 3 22 6.58172 22 11C22 15.4183 18.4183 19 14 19V22.5C9 20.5 2 17.5 2 11C2 6.58172 5.58172 3 10 3Z">
                </path>
            </svg>
            Chat
        </a>
    {% endif %}
    <a href="{% url 'chatbot:emotion' %}" role="menuitem">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor">
            <path d="M2 13H8V21H2V13ZM9 3H15V21H9V3ZM16 8H22V21H16V8Z"></path>
        </svg>

        Log
    </a>
    <a href="{% url 'character:trash' %}" role="menuitem" class="active">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor">
            <path
                    d="M17 6H22V8H20V21C20 21.5523 19.5523 22 19 22H5C4.44772 22 4 21.5523 4 21V8H2V6H7V3C7 2.44772 7.44772 2 8 2H16C16.5523 2 17 2.44772 17 3V6ZM9 11V17H11V11H9ZM13 11V17H15V11H13ZM9 4V6H15V4H9Z">
            </path>
        </svg>
        Trash
    </a>
    <a href="{% url 'users:profile' %}" role="menuitem">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor">
            <path
                    d="M20 22H4V20C4 17.2386 6.23858 15 9 15H15C17.7614 15 20 17.2386 20 20V22ZM12 13C8.68629 13 6 10.3137 6 7C6 3.68629 8.68629 1 12 1C15.3137 1 18 3.68629 18 7C18 10.3137 15.3137 13 12 13Z">
            </path>
        </svg>
        Profile
    </a>

    <i class="line" id="nav-current">current item</i>
</nav>
<!--아이콘 추가된 부분 -->
<!-- <h1>Feelbuddy</h1> -->
<div id="pole">
    <div id="right">
        <div class="logo"><b>T<span>R</span>A<span>S</span>H</b></div>
    </div>
</div>
<div class="icon">
    <a href="{% url 'character:character_list' %}">
        <div class="icon__home">

            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor">
                <path
                        d="M20 20C20 20.5523 19.5523 21 19 21H5C4.44772 21 4 20.5523 4 20V11L1 11L11.3273 1.6115C11.7087 1.26475 12.2913 1.26475 12.6727 1.6115L23 11L20 11V20ZM11 13V19H13V13H11Z">
                </path>
            </svg>

        </div>
    </a>
    <a href="{% url 'users:profile' %}">
        <div class="icon__account">

            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor">
                <path
                        d="M20 22H4V20C4 17.2386 6.23858 15 9 15H15C17.7614 15 20 17.2386 20 20V22ZM12 13C8.68629 13 6 10.3137 6 7C6 3.68629 8.68629 1 12 1C15.3137 1 18 3.68629 18 7C18 10.3137 15.3137 13 12 13Z">
                </path>
            </svg>

        </div>
    </a>
    {% if first_item %}
        <a href="{% url 'chatbot:chatbot_content_list' first_item.pk %}">
            <div class="icon__chat">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor">
                    <path
                            d="M10 3H14C18.4183 3 22 6.58172 22 11C22 15.4183 18.4183 19 14 19V22.5C9 20.5 2 17.5 2 11C2 6.58172 5.58172 3 10 3Z">
                    </path>
                </svg>
            </div>
        </a>
    {% endif %}
    <a href="{% url 'feedback:feedback_list' %}">
        <div class="icon__log">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor">
                <path d="M21.9024 10.5976C21.4442 10.5333 20.976 10.5 20.5 10.5C17.2404 10.5 14.3455 12.0604 12.5212 14.471C12.3501 14.4887 12.1763 14.4978 12 14.4978C10.7188 14.4978 9.55217 14.0172 8.66691 13.2248L7.33309 14.7151C8.41871 15.6868 9.81141 16.3253 11.3466 16.4676C10.8023 17.7016 10.5 19.0662 10.5 20.5C10.5 20.976 10.5333 21.4442 10.5976 21.9024C5.7387 21.2205 2 17.0469 2 12C2 6.47715 6.47715 2 12 2C17.0469 2 21.2205 5.7387 21.9024 10.5976ZM21.8707 12.617C21.4254 12.5401 20.9674 12.5 20.5 12.5C17.7656 12.5 15.3512 13.8709 13.9068 15.9675C13.0194 17.2556 12.5 18.8156 12.5 20.5C12.5 20.9674 12.5401 21.4254 12.617 21.8707L21.8707 12.617ZM8.5 11.5C9.32843 11.5 10 10.8284 10 10C10 9.17157 9.32843 8.5 8.5 8.5C7.67157 8.5 7 9.17157 7 10C7 10.8284 7.67157 11.5 8.5 11.5ZM15.5 11.5C16.3284 11.5 17 10.8284 17 10C17 9.17157 16.3284 8.5 15.5 8.5C14.6716 8.5 14 9.17157 14 10C14 10.8284 14.6716 11.5 15.5 11.5Z"></path>
            </svg>

        </div>
    </a>
    <a href="{% url 'chatbot:emotion' %}">
        <div class="icon__log">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor">
                <path d="M2 13H8V21H2V13ZM9 3H15V21H9V3ZM16 8H22V21H16V8Z"></path>
            </svg>

        </div>
    </a>
    <a href="{% url 'character:trash' %}">
        <div class="icon__delete">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor">
                <path
                        d="M17 6H22V8H20V21C20 21.5523 19.5523 22 19 22H5C4.44772 22 4 21.5523 4 21V8H2V6H7V3C7 2.44772 7.44772 2 8 2H16C16.5523 2 17 2.44772 17 3V6ZM9 11V17H11V11H9ZM13 11V17H15V11H13ZM9 4V6H15V4H9Z">
                </path>
            </svg>
        </div>
    </a>
    <!-- 여기 로그아웃 링크 클래스명 달아주세요! -->
    <a class="logout-btn" style="cursor: pointer;">
        <div class="icon__logout">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor">
                <path d="M12 22C6.47715 22 2 17.5228 2 12C2 6.47715 6.47715 2 12 2C15.2713 2 18.1757 3.57078 20.0002 5.99923L17.2909 5.99931C15.8807 4.75499 14.0285 4 12 4C7.58172 4 4 7.58172 4 12C4 16.4183 7.58172 20 12 20C14.029 20 15.8816 19.2446 17.2919 17.9998L20.0009 17.9998C18.1765 20.4288 15.2717 22 12 22ZM19 16V13H11V11H19V8L24 12L19 16Z"></path>
            </svg>

        </div>
    </a>

</div>

<!-- 추가된 부분 -->
<div class="carousel">

    <div class="carousel-control-button left"><input type="radio" name="carousel-control-input"></div>
    <div class="carousel-control-button right"><input type="radio" name="carousel-control-input" checked></div>

    <div class="carousel-rotation-direction">

        <ul class="carousel-item-wrapper" style="--_num-elements: 5">

            {% for trash in character_trash %}
                <li class="carousel-item"
                    data-id="{{ trash.id }}"
                    style="--_index: {{ forloop.counter }}; --_image-url: url('{{ trash.adminCharacter.image.url }}')">
                    <a href="#" target="_blank">{{ trash.name }}</a>
                </li>
            {% endfor %}

            <li class="carousel-ground"></li>

        </ul>

    </div>

</div>
<script>
    document.querySelectorAll('.logout-btn').forEach(button => {
        button.addEventListener('click', function (event) {
            event.preventDefault();  // 기본 동작 막기

            const csrfToken = "{{ csrf_token }}";  // CSRF 토큰 가져오기 (Django 템플릿에서)
            const logoutUrl = "{% url 'users:logout' %}";  // 로그아웃 URL 가져오기

            fetch(logoutUrl, {
                method: 'POST',  // POST 방식으로 요청
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': csrfToken  // CSRF 토큰을 헤더에 포함
                },
                body: JSON.stringify({})  // 필요한 경우 데이터를 여기에 추가
            })
                .then(response => {
                    if (response.ok) {
                        window.location.href = "/";  // 로그아웃 성공 시 리디렉션할 페이지 설정
                    } else {
                        console.error('로그아웃 실패');
                    }
                })
                .catch(error => console.error('에러 발생:', error));
        });
    });
</script>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        const items = document.querySelectorAll('.carousel-item');

        items.forEach(item => {
            item.addEventListener('click', function (event) {
                event.preventDefault();
                const itemName = item.querySelector('a').textContent;
                const itemId = item.getAttribute('data-id');
                const restoreUrl = `/trash/restore/${itemId}`;
                const deleteUrl = `/trash/perfect/delete/${itemId}`;

                // 복구 여부 확인
                if (confirm(`"${itemName}" 항목을 복구하시겠습니까?`)) {
                    // 복구를 선택했을 경우 POST 요청 전송
                    fetch(restoreUrl, {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json',
                            'X-CSRFToken': getCsrfToken() // CSRF 토큰을 포함시켜야 함
                        },
                        body: JSON.stringify({}) // POST 요청의 본문 (필요시 데이터 추가)
                    }).then(response => {
                        if (response.ok) {
                            window.location.href = restoreUrl; // 요청 후 리디렉션
                        } else {
                            alert('복구 요청 처리 중 오류가 발생했습니다.');
                        }
                    });
                } else {
                    // 복구를 선택하지 않았을 경우 삭제 여부 확인
                    if (confirm(`"${itemName}" 항목을 삭제하시겠습니까?`)) {
                        // 삭제를 선택했을 경우 POST 요청 전송
                        fetch(deleteUrl, {
                            method: 'POST',
                            headers: {
                                'Content-Type': 'application/json',
                                'X-CSRFToken': getCsrfToken() // CSRF 토큰을 포함시켜야 함
                            },
                            body: JSON.stringify({}) // POST 요청의 본문 (필요시 데이터 추가)
                        }).then(response => {
                            if (response.ok) {
                                window.location.href = deleteUrl; // 요청 후 리디렉션
                            } else {
                                alert('삭제 요청 처리 중 오류가 발생했습니다.');
                            }
                        });
                    }
                }
            });
        });

        function getCsrfToken() {
            // 페이지에서 CSRF 토큰을 찾는 함수
            const csrfToken = document.querySelector('meta[name="csrf-token"]').getAttribute('content');
            return csrfToken;
        }
    });
</script>
</body>

</html>