character/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static

app_name = 'character'
urlpatterns = [

    # 캐릭터 생성 관련 페이지

    path('character/list', character_list, name='character_list'),  # 생성한 캐릭터 리스트 페이지

    path('character/detail/<int:pk>', character_detail, name='character_detail'),  # 캐릭터 디테일 페이지

    path('character/create', character_create, name='character_create'),  # 캐릭터 5개 있는 페이지 선택

    # 캐릭터 하나를 선택하고 들어온 그 text 페이지 여기서는 선택이유 쓰면 됨  결국 이 텍스트는 introudce에 저장 추가로 캐릭터 이름도 적어야됨
    path('character/create/<int:pk>', character_create_detail, name='character_create_detail'),

    path('character/update/<int:pk>', character_update, name='character_update'),
    # 캐릭터 이름만 수정                   {{ 차이 }} --> 캐릭터의 이름은 감정 그 자체로 해서 변화시킬 수 없는것으로 구상한것이었음

    path('trash/delete/<int:pk>', trash_delete, name='trash_delete'),  # 이거는 캐릭터 삭제버튼 url 즉 휴지통으로  이동 post 만 접속가능하게 해야됨

    path('trash', trash, name='trash'),  # 여기는 삭제된 캐릭터의 휴지통 페이지

    path('trash/restore/<int:pk>', trash_restore, name='trash_restore'),
    # 여기는 휴지통에서 캐릭터 선택하면 복구하는 페이지 만약 복구했는데 캐릭터 5개이면 복구못하게

    path('trash/perfect/delete/<int:pk>', trash_perfect_delete, name='trash_perfect_delete'),
    # 이거는 캐릭터 영구 삭제 url 즉 휴지통에서만 작동할수 있는 url임


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


# 404 핸들러
from django.shortcuts import render

def custom_page_not_found_view(request, exception):
    return render(request, '404.html', {}, status=404)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('feedback.urls')),
    path('', include('chatbot.urls')),
    path('', include('character.urls')),
    path('accounts/', include('allauth.urls')), #소셜로그인

]

# DEBUG가 False여도 미디어 파일 서빙 가능하게 설정
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# 이미지 파일 서빙을 위해 추가
# if not settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# 404 핸들러 설정
handler404 = 'config.urls.custom_page_not_found_view'

feedback/urls.py
from django.urls import path
from .views import *

app_name = 'feedback'
urlpatterns = [
    path('community/', feedback_list, name='feedback_list'),
    path('community/create/', feedback_create, name='feedback_create'),
    path('community/delete/<int:pk>/', feedback_delete, name='feedback_delete'),
    path('community/detail/<int:pk>/', feedback_detail, name='feedback_detail'),
    path('edit/<int:pk>/', feedback_edit, name='feedback_edit'),
]

users/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

app_name = 'users'

urlpatterns = [

    # 메인
    path('', main, name='main'),

    # 회원
    path('signup/', signup, name='signup'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('profile/', profile, name='profile'),

    #비밀번호 찾기
    path('password_reset/', password_reset_request, name='password_reset'), #비밀번호 재설정 요청 폼
    path('password_reset/done/', password_reset_done, name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', password_reset_confirm, name='password_reset_confirm'), #새 비밀번호 설정 폼
    path('password_reset_complete/', password_reset_complete, name='password_reset_complete'), #비밀번호 재설정 완료 페이지
]

users/models.py
import uuid
from django.db import models
from django.contrib.auth.models import AbstractUser
import random
import re
from django.core.exceptions import ValidationError


def validate_username(value):
    if not re.match(r'^[a-zA-Z0-9]+$', value):
        raise ValidationError('아이디는 영문자와 숫자만 사용할 수 있습니다.')


class User(AbstractUser):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=15, null=True)
    email = models.EmailField()
    username = models.CharField(
        max_length=20,
        unique=True,
        validators=[validate_username],
        error_messages={
            'unique': "이미 사용 중인 아이디입니다.",
        },
    )

class NumViews(models.Model):
    count = models.PositiveIntegerField(default=0)  # 조회수를 저장하는 필드, 기본값 0

    def increment(self):
        self.count += 1
        self.save()

    def __str__(self):
        return f'조회수: {self.count}'

# class Profile(models.Model):
#     user = models.OneToOneField(User, on_delete=models.CASCADE)
#     nickname = models.CharField(max_length=10, blank=True)
#     profile_picture = models.ImageField(upload_to='profile_pics/', blank=True)

#     def __str__(self):
#         return self.user.username

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nickname = models.CharField(max_length=20, blank=True)
    profile_picture = models.ImageField(upload_to='profile_pics/', blank=True)

    def save(self, *args, **kwargs):
        if not self.nickname:
            random_names = [
                '화사한 유채꽃',
                '푸른 바다',
                '밝은 햇살',
                '고요한 달빛',
                '필버디',
                '돼지와 함께 춤을',
                '마법사의 주문',
                '피자와 콜라의 전쟁',
                '구름 위의 트램펄린',
                '레몬으로 만든 로켓',
                '슈퍼히어로의 휴식처',
                '달콤한 초콜릿 폭풍',
                '햄버거의 비밀 파티',
                '시간 여행자의 소원',
                '고양이의 비밀 카페',
                '우주에서 온 보물상자',
                '치즈와 함께 춤추다',
                '버터플라이의 대모험',
                '별빛이 내린 저녁',
                '산 속의 비밀 레시피',
                '몽환의 자판기',
                '미래의 구름 조각',
                '신비한 떡볶이 연구소',
                '달나라의 파자마 파티',
                '무지개 속의 미스테리',
                '시간을 달리는 고양이',
                '우주 제일의 딸기케이크',
                '어둠 속의 판타지 오페라',
                '거울 속의 마법사',
                '해리포터의 비밀 열쇠',
                '우주정거장의 피자 파티',
                '잃어버린 별의 연대기',
                '반짝이는 치즈폭탄',
                '시간의 모래시계',
                '미로 속의 레몬 에이드',
                '전설의 아이스크림 공장',
                '마법의 연필과 그림자'
            ]

            self.nickname = random.choice(random_names)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.user.username


from django.db.models.signals import post_save
from django.dispatch import receiver


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'name', 'email', 'password1', 'password2')

users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login as auth_login, authenticate, logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm

from character.models import UserCharacter
from .forms import SignUpForm
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .models import Profile, User, validate_username, NumViews
from django.contrib.auth.tokens import default_token_generator
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.core.mail import EmailMessage
from django.contrib.auth.forms import PasswordResetForm, SetPasswordForm
from django.http import HttpResponse
from django.conf import settings
from django.core.mail import send_mail
from django.contrib.auth.hashers import make_password
from django.http import JsonResponse
from django.core.exceptions import ValidationError
#닉네임 랜덤 생성
from django.core.exceptions import ObjectDoesNotExist
import random
# Create your views here.


def main(request):
    user = request.user
    num_views = NumViews.objects.get(id=1)  # 원하는 객체의 ID를 사용하세요.
    num_views.increment()  # 조회수 1 증가

    if user.is_anonymous:  # 로그인하지 않은 사용자인 경우 ######
        display_name = "Anonymous User"
    else:
        try:
            profile = Profile.objects.get(user=user)
            display_name = profile.nickname  # 2차 수정
        except ObjectDoesNotExist:
            random_names = ['화사한 유채꽃', '푸른 바다', '밝은 햇살', '고요한 달빛']
            display_name = random.choice(random_names)

    context = {
        'display_name': display_name
    }

    return render(request, 'user/main.html', context)

def signup(request):
    if request.user.is_authenticated:
        return redirect('users:main')  # 로그인된 사용자는 메인 화면으로 리디렉션

    if request.method == 'POST':
        print('gd')
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')
        name = request.POST.get('name')
        # 사용자 존재 여부 확인
        if User.objects.filter(username=username).exists():
            return render(request, 'user/signup.html', {'error': '이미 사용 중인 사용자 이름입니다.'})

        if User.objects.filter(email=email).exists():
            return render(request, 'user/signup.html', {'error': '이미 사용 중인 이메일 주소입니다.'})
        try:
            # 아이디가 영문자와 숫자로 이루어졌는지 확인
            validate_username(username)

            user = User.objects.create(
                username=username,
                email=email,
                name=name,
            )
            user.set_password(password)  # 비밀번호 해시화
            user.save()

            ################### 프로필 객체 생성 및 닉네임 할당 (2차 수정)
            # 이미 존재하는지 확인
            if not Profile.objects.filter(user=user).exists():
                profile = Profile.objects.create(user=user)
                profile.nickname = profile.get_random_nickname()
                profile.save()

            return redirect('users:login')
        except ValidationError as e:
            error_message = " ".join(e.messages)
            return render(request, 'user/signup.html', {'error': f'회원가입에 실패했습니다: {error_message}'})
        except Exception as e:
            return render(request, 'user/signup.html', {'error': f'회원가입에 실패했습니다: {str(e)}'})

    return render(request, 'user/signup.html')


def login(request):
    if request.user.is_authenticated:
        return redirect('users:main')  # 로그인된 사용자는 메인 화면으로 리디렉션
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)
        if user is not None:
            auth_login(request, user)
            return redirect('character:character_list')
        else:
            return render(request, 'user/signup.html', {'error': '일치하는 계정이 없습니다.'})
    return render(request, 'user/signup.html')


@login_required
def logout(request):
    if request.method == "POST":
        auth_logout(request)
        return redirect('users:main')
    return redirect('users:main')

@login_required
def profile(request):
    user = request.user
    profile, created = Profile.objects.get_or_create(user=user)

    if request.method == 'POST':
        nickname = request.POST.get('nickname', profile.nickname)  # 기존 닉네임 유지
        profile_picture = request.FILES.get('profile_picture')

        profile.nickname = nickname  # 닉네임 업데이트
        if profile_picture:
            profile.profile_picture = profile_picture  # 프로필 사진 업데이트

        profile.save()

        response_data = {
            'nickname': profile.nickname,
            'profile_picture_url': profile.profile_picture.url if profile.profile_picture else ''
        }
        return JsonResponse(response_data)
    first_item = UserCharacter.objects.filter(user=request.user, trash=False).first()
    context = {
        'user': user,
        'profile': profile,
        'first_item':first_item
    }

    return render(request, 'user/profile.html', context)

#비밀번호 재설정 요청
def password_reset_request(request):
    if request.method == 'POST':
        step = request.session.get('password_reset_step', 1)

        if step == 1: #1단계: 사용자 id 확인
            username = request.POST.get('username')
            try:
                user = User.objects.get(username=username)
                request.session['password_reset_username'] = username
                request.session['password_reset_step'] = 2
                return render(request, 'user/password_reset.html', {'step': 2})
            except User.DoesNotExist:
                return render(request, 'user/password_reset.html', {'step': 1, 'error': 'Username not found.'})

        elif step == 2: #2단계: 회원정보에 등록된 이메일 입력
            email = request.POST.get('email')
            username = request.session.get('password_reset_username')
            user = get_object_or_404(User, username=username)

            #입력 받은 이메일이 회원 정보와 일치하는지 확인 후 이메일 전송
            if user.email == email:
                token = default_token_generator.make_token(user)
                uid = urlsafe_base64_encode(force_bytes(user.pk))

                email_subject = 'FeelBuddy: 비밀번호 재설정 메일'
                email_body = render_to_string('user/password_reset_email.txt', {
                    'user': user,
                    'domain': request.get_host(),
                    'uid': uid,
                    'token': token,
                    'protocol': 'http',
                })

                #비밀번호 재설정 이메일 전송
                send_mail(
                    email_subject,
                    email_body,
                    settings.EMAIL_HOST_USER,
                    [email],
                    fail_silently=False,
                )

                request.session['password_reset_step'] = 1
                return redirect('users:password_reset_done')
            else:
                #이메일 일치하지 않을 경우 오류메시지
                return render(request, 'user/password_reset.html', {'step': 2, 'error': 'Email does not match the registered email.'})

    else:
        request.session['password_reset_step'] = 1
        return render(request, 'user/password_reset.html', {'step': 1})

#비밀번호 재설정 요청이 완료된 후 보여줄 페이지
def password_reset_done(request):
    return render(request, 'user/password_reset_done.html')

#비밀번호 재설정 링크를 통해 접근할 뷰
def password_reset_confirm(request, uidb64=None, token=None):
    if uidb64 is None or token is None:
        return redirect('users:password_reset')  # uidb64 또는 token이 없는 경우 처리

    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = get_object_or_404(User, pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        if request.method == 'POST':
            new_password1 = request.POST.get('new_password1')
            new_password2 = request.POST.get('new_password2')

            if new_password1 and new_password2 and new_password1 == new_password2:
                user.password = make_password(new_password1)  # 비밀번호 해시화
                user.save()
                return redirect('users:password_reset_complete')
            else:
                return render(request, 'user/password_reset_confirm.html', {
                    'error': 'Passwords do not match.',
                })
    else:
        return render(request, 'user/password_reset_confirm.html', {
            'error': 'Invalid password reset link.',
        })

    return render(request, 'user/password_reset_confirm.html')

#비밀번호 재설정 완료
def password_reset_complete(request):
    return render(request, 'user/password_reset_complete.html')

templates/user/login.html
{% block content %}
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" id="username" name="username" required><br><br>
    <label for="password">Password:</label>
    <input type="password" id="password" name="password" required><br><br>
    <button type="submit">Login</button>
    {% if error %}
    <p style="color: red;">{{ error }}</p>
    {% endif %}
  </form>
{% endblock %}

templates/user/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FeelBuddy</title>
    <link rel="stylesheet" href="{% static '/css/user/main.css' %}">
    <link rel="stylesheet" href="/static/mobile/momain.css">
    <link rel="icon" href="/media/joy.png" type="image/png">
 <!-- Open Graph Meta Tags -->
    <meta property="og:url" content="https://www.feelbuddy.kr"/>
    <meta property="og:title" content="Feelbuddy - 감정 치유 플랫폼"/>
    <meta property="og:description" content="Feelbuddy에서 당신의 감정을 공유하고 공감하여 마음을 치유하세요!"/>
    <meta property="og:type" content="website"/>
    <meta property="og:image" content="https://feelbuddy.kr/media/logo2.png"/>

</head>

<body>
<div class="stars"></div>
<div class="poster-center">
    <article id="furiosa_poster">
        <header id="furiosa_poster__header">
            <h1 id="furiosa_poster__header__title" data-title="Feelbuddy">Feelbuddy</h1>
        </header>
    </article>
</div>
<div id="game-and-watch" class="nintendo">
    <div id="game-and-watch-screen-sheen">
        <!-- 화면 -->
        <div id="game-and-watch-screen-sheen-in"></div>
    </div>

    <div id="game-and-watch-case">

        <div id="game-and-watch-case-in">
            <div id="mini-classic-logo" class="temp-hack">Joy</div>


            <!-- #왼쪽 파트 -->
            <div id="game-and-watch-left">
                <div id="game-and-watch-badge"><img src="/media/logo2.png" alt="" class="" width="110px" height="110px">
                </div>
                <div id="game-and-watch-character">
                    <!-- <img src="/logo1.jpeg" alt="" class="" width="80px" height="80px"> -->

                </div>
                <div id="game-and-watch-leftbutton">
                    <div id="game-and-watch-leftbutton-horizontal"></div>
                    <div id="game-and-watch-leftbutton-vertical">
                        <div id="game-and-watch-leftbutton-top">
                            <a href="#"></a>
                        </div>
                        <div id="game-and-watch-leftbutton-cover">
                        </div>
                        <div id="game-and-watch-leftbutton-bottom">
                            <a href="#"></a>
                        </div>
                        <div id="game-and-watch-leftbutton-left">
                            <a href="#" id="left-button"></a>
                        </div>
                        <div id="game-and-watch-leftbutton-right">
                            <!-- <a href="#rightbut"></a> -->
                            <a href="#" id="right-button"></a>
                        </div>
                    </div>
                    <span>&larr; &uarr; &darr; &rarr;</span> Control
                </div>
            </div>
            <!-- 스크린 위의 입체 -->
            <div id="game-and-watch-screen">


                <div id="game-and-watch-screen-top"></div>
                <div id="game-and-watch-screen-in">

                    <div id="game-and-watch-game-title">당신의 감정을 친구로 만들어주는 마음 관리 플랫폼<span></span></div>
                    <div id="game-and-watch-game">
                        <img src="/media/joy.png" id="main-image" alt="" class="joy" width="200px" height="auto">

                        <div id="game-and-watch-level-two">

                        </div>
                        <div id="game-and-watch-level-one">

                        </div>
                    </div>
                    <div id="game-and-watch-nintendo-logo">joy</div>
                </div>
                <div id="game-and-watch-screen-bottom"></div>
            </div>
            <div id="game-and-watch-gameboy-title"><span>Nintendo</span> Game Boy &trade;</div>
            <div id="game-and-watch-right">
                <div id="game-and-watch-game-start">
                    {% if user.is_authenticated %}
                        <div id="game-and-watch-start-one">
                            <div class="game-and-watch-start-inner">
                            <a class="logout-btn" style="cursor: pointer;"><p>Logout</p></a>

                            </div>
                        </div>
                    {% else %}
                        <div id="game-and-watch-start-one">
                            <div class="game-and-watch-start-inner"><a href="{% url 'users:login' %}"><p>Login</p></a></div>
                        </div>
                        <div id="game-and-watch-gamea-text"></div>
                        <div id="game-and-watch-start-two">
                            <div class="game-and-watch-start-inner"><a href="{% url 'users:signup' %}"><p>SignUp</p></a></div>
                        </div>
                    {% endif %}
                    <div id="game-and-watch-gameb-text"></div>
                    <div id="game-and-watch-start-three">
                        <div class="game-and-watch-start-inner">
                            <a href="{% url 'feedback:feedback_list' %}"><p>Review</p></a>
                        </div>

                    </div>
                    <div id="game-and-watch-time-text"></div>
                    <div id="gameboy-settings-text">
                        <div id="gameboy-start-text"></div>
                    </div>

                </div>
                <div id="game-and-watch-game-settings">
                       {% if user.is_authenticated %}
                    <div id="game-and-watch-game-tiny-pinhole">       <a class="logout-btn" style="cursor: pointer;"><p>Logout</p></a>
</div>
                    <div id="game-and-watch-game-tiny-pinhole"><a href="{% url 'feedback:feedback_list' %}">Review</a></div>

                             {% else %}
                    <!-- 미니 핀홀 버튼 -->
                    <div id="game-and-watch-game-tiny-pinhole"><a href="{% url 'users:login' %}">Login</a></div>
                    <div id="game-and-watch-game-tiny-pinhole"><a href="{% url 'users:signup' %}">SignUp</a></div>
                    <div id="game-and-watch-game-tiny-pinhole"><a href="{% url 'feedback:feedback_list' %}">Review</a></div>

                              {% endif %}
                </div>
                <div id="game-and-watch-rightbutton">
                    <div id="mini-classic-rightbutton-text"></div>
                    <!-- 중간 start 버튼 -->
                    <div id="game-and-watch-rightbutton-in">
                        <a href="{% url 'character:character_list' %}" >
                            <p>Start</p>
                        </a>
                    </div>
                    <!-- 웹 start 버튼 -->
                    <div id="game-and-watch-rightbutton-text">Start</div>
                </div>

                <!-- 모바일 start 버튼 -->
                <div id="gameboy-rightbutton-in"><a href="{% url 'feedback:feedback_list' %}"><p>Review</p></a></div>

            </div>
            <!-- <div id="gameboy-button-text-a">A</div>
            <div id="gameboy-button-text-b">B</div>
            <div id="game-and-watch-gameboy-speaker">
                <ul>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                </ul>
            </div>
            <div id="game-and-watch-left-gloss"></div>
            <div id="game-and-watch-right-gloss"></div> -->
        </div>
    </div>

    <div id="game-and-watch-bottom-edge"></div>
    <div id="game-and-watch-bottom-edgetwo"></div>
    <div id="game-and-watch-bottom-edgeshadow"></div>


    <div class="land">
        <div class="warp warp-one">
            <div class="warp-top"></div>
            <div class="warp-body"></div>
        </div>

        <div class="warp warp-two">
            <div class="warp-top"></div>
            <div class="warp-body"></div>
        </div>
        <div class="clear"></div>
        <div class="mud">
            <div class="mud-strip"></div>
            <div class="mud-strip"></div>
        </div>

    </div>
</div>
<div class="gradients-container">
    <div class="g1"></div>
    <div class="g2"></div>
    <div class="g3"></div>
    <div class="g4"></div>
    <div class="g5"></div>
    <div class="interactive"></div>
</div>
<script>
document.querySelectorAll('.logout-btn').forEach(button => {
    button.addEventListener('click', function(event) {
        event.preventDefault();  // 기본 동작 막기

        const csrfToken = "{{ csrf_token }}";  // CSRF 토큰 가져오기 (Django 템플릿에서)
        const logoutUrl = "{% url 'users:logout' %}";  // 로그아웃 URL 가져오기

        fetch(logoutUrl, {
            method: 'POST',  // POST 방식으로 요청
            headers: {
                'Content-Type': 'application/json',
                'X-CSRFToken': csrfToken  // CSRF 토큰을 헤더에 포함
            },
            body: JSON.stringify({})  // 필요한 경우 데이터를 여기에 추가
        })
        .then(response => {
            if (response.ok) {
                window.location.href = "/";  // 로그아웃 성공 시 리디렉션할 페이지 설정
            } else {
                console.error('로그아웃 실패');
            }
        })
        .catch(error => console.error('에러 발생:', error));
    });
});
</script>



<script src="{% static '/js/user/main.js' %}"></script>
</body>

</html>

templates/user/password_reset.html
{% load static %}
<!DOCTYPE html>
<html lang="es" dir="ltr">
<head>
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0">
    <meta charset="utf-8">
    <title>FeelBuddy</title>
    <link rel="icon" href="/media/joy.png" type="image/png">
    <link rel="stylesheet" href="{% static '/css/user/pw_reset.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/static/login.css">
</head>
<body>
<link rel="stylesheet" href="{% static '/css/user/login.css' %}">
<div class="main">
  <div class="container a-container">
    <form class="form" method="post">
      {% csrf_token %}
      
      {% if step == 1 %}
      <h2 class="title">비밀번호 찾기</h2>
      <h3 class="description">비밀번호를 찾고자 하는 아이디를 입력해주세요.</h3>
      <input class="form__input" type="text" id="username" name="username" placeholder="아이디" required>
      <button class="button" type="submit">다음</button>

      {% elif step == 2 %}
      <h2 class="title">이메일 확인</h2>
      <h3 class="description">회원정보에 등록한 이메일을 입력해주세요.</h3>
      <input class="form__input" type="email" id="email" name="email" placeholder="이메일" required>
      <button class="button" type="submit">다음</button>

      {% endif %}

      {% if error %}
      <p style="color: red;">{{ error }}</p>
      {% endif %}
    </form>
  </div>
</div>

templates/user/password_reset_complete.html
{% load static %}
<!DOCTYPE html>
<html lang="ko" dir="ltr">
<head>
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0">
    <meta charset="utf-8">
    <title>FeelBuddy</title>
    <link rel="icon" href="/media/joy.png" type="image/png">
    <link rel="stylesheet" href="{% static '/css/user/pw_reset.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700;800&display=swap" rel="stylesheet">
</head>
<body>
<div class="main">
    <div class="container">
        {% block content %}
        <h2 class="form_title title title-black">비밀번호 재설정 완료</h2>
        <p>비밀번호가 성공적으로 재설정되었습니다. <br>이제 <a href="{% url 'users:login' %}">로그인</a>할 수 있습니다.</p>
        {% endblock %}
    </div>
</div>
</body>
</html>

templates/user/password_reset_done.html
{% load static %}
<!DOCTYPE html>
<html lang="ko" dir="ltr">
<head>
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0">
    <meta charset="utf-8">
    <title>FeelBuddy</title>
    <link rel="icon" href="/media/joy.png" type="image/png">
    <link rel="stylesheet" href="{% static '/css/user/pw_reset.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700;800&display=swap" rel="stylesheet">
</head>
<body>
<div class="main">
    <div class="container">
        {% block content %}
        <h2 class="form_title title title-black">비밀번호 재설정 요청 완료</h2>
        <p>입력하신 이메일 주소로 비밀번호 재설정 메일을 발송했습니다. 메일함을 확인하여 비밀번호를 재설정해 주세요.</p>
        {% endblock %}
    </div>
</div>
</body>
</html>